/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-elevated": "var(--color-surface-elevated)",
        hover: "var(--color-hover)",
        border: "var(--color-border)",
        text: {
          DEFAULT: "var(--color-text)",
          secondary: "var(--color-text-secondary)",
        },
        muted: "var(--color-muted)",
        primary: "var(--color-primary)",
        card: "var(--color-card)",
        sidebar: "var(--color-sidebar)",
        /* Omni naturals palette */
        "naturals-n0":  "var(--color-naturals-n0)",
        "naturals-n1":  "var(--color-naturals-n1)",
        "naturals-n2":  "var(--color-naturals-n2)",
        "naturals-n3":  "var(--color-naturals-n3)",
        "naturals-n4":  "var(--color-naturals-n4)",
        "naturals-n5":  "var(--color-naturals-n5)",
        "naturals-n6":  "var(--color-naturals-n6)",
        "naturals-n7":  "var(--color-naturals-n7)",
        "naturals-n8":  "var(--color-naturals-n8)",
        "naturals-n9":  "var(--color-naturals-n9)",
        "naturals-n10": "var(--color-naturals-n10)",
        "naturals-n11": "var(--color-naturals-n11)",
        "naturals-n12": "var(--color-naturals-n12)",
        "naturals-n13": "var(--color-naturals-n13)",
        "naturals-n14": "var(--color-naturals-n14)",
        /* Omni primary palette */
        "primary-p1": "var(--color-primary-p1)",
        "primary-p2": "var(--color-primary-p2)",
        "primary-p3": "var(--color-primary-p3)",
        "primary-p4": "var(--color-primary-p4)",
        "primary-p5": "var(--color-primary-p5)",
        "primary-p6": "var(--color-primary-p6)",
        /* Omni semantic named colors */
        "green-g1": "var(--color-green-g1)",
        "green-g2": "var(--color-green-g2)",
        "red-r1":   "var(--color-red-r1)",
        "red-r2":   "var(--color-red-r2)",
        "yellow-y1": "var(--color-yellow-y1)",
        "yellow-y2": "var(--color-yellow-y2)",
        "blue-b1":  "var(--color-blue-b1)",
        /* Icon / status */
        "icon-success": "var(--color-icon-success)",
        "icon-warning": "var(--color-icon-warning)",
        "icon-danger": "var(--color-icon-danger)",
        "icon-info": "var(--color-icon-info)",
        /* Dashboard status colors */
        "dashboard-success": "var(--color-dashboard-success)",
        "dashboard-success-bg": "var(--color-dashboard-success-bg)",
        "dashboard-warning": "var(--color-dashboard-warning)",
        "dashboard-warning-bg": "var(--color-dashboard-warning-bg)",
        "dashboard-danger": "var(--color-dashboard-danger)",
        "dashboard-danger-bg": "var(--color-dashboard-danger-bg)",
        "dashboard-info": "var(--color-dashboard-info)",
        "dashboard-info-bg": "var(--color-dashboard-info-bg)",
        /* Dashboard metric colors */
        "dashboard-metric-primary": "var(--color-dashboard-metric-primary)",
        "dashboard-metric-primary-bg": "var(--color-dashboard-metric-primary-bg)",
        "dashboard-metric-secondary": "var(--color-dashboard-metric-secondary)",
        "dashboard-metric-secondary-bg": "var(--color-dashboard-metric-secondary-bg)",
        "dashboard-metric-tertiary": "var(--color-dashboard-metric-tertiary)",
        "dashboard-metric-tertiary-bg": "var(--color-dashboard-metric-tertiary-bg)",
        "dashboard-metric-quaternary": "var(--color-dashboard-metric-quaternary)",
        "dashboard-metric-quaternary-bg": "var(--color-dashboard-metric-quaternary-bg)",
      },
      fontFamily: {
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      spacing: {
        "safe": "var(--radius-md)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-sidebar)",
      },
      transitionDuration: {
        fast: "var(--transition-fast)",
        normal: "var(--transition-normal)",
      },
    },
  },
  plugins: [],
}
