services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-1.0.0-dev}
    image: pertisk-kube-web:${VERSION:-1.0.0-dev}
    container_name: pertisk-kube-web
    ports:
      - "8092:8091"
      - "50052:50051"
    environment:
      RUST_LOG: info
      KUBECONFIG: /home/appuser/.kube/config
    volumes:
      - ${HOME}/.kube/config:/home/appuser/.kube/config:ro
      - ${HOME}/.aws:/home/appuser/.aws:ro
    restart: unless-stopped
