 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: pertisk-kube-frontend
   namespace: pertisk-kube
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: pertisk-kube-frontend
   template:
     metadata:
       labels:
         app: pertisk-kube-frontend
     spec:
       containers:
         - name: frontend
           image: your-registry/pertisk-kube-frontend:latest
           imagePullPolicy: IfNotPresent
           env:
            - name: BACKEND_URL
               value: "http://pertisk-kube-backend.pertisk-kube.svc.cluster.local:8091/api"
           ports:
             - containerPort: 3000
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: pertisk-kube-frontend
   namespace: pertisk-kube
 spec:
   selector:
     app: pertisk-kube-frontend
   ports:
     - name: http
       port: 80
       targetPort: 3000

