 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: pertisk-kube-frontend
   namespace: pertisk-kube
   annotations:
     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
 spec:
   rules:
     - host: pertisk-kube.local
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: pertisk-kube-frontend
                 port:
                   number: 80

