 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: pertisk-kube-sa
   namespace: pertisk-kube
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRole
 metadata:
   name: pertisk-kube-readonly
 rules:
   - apiGroups: [""]
     resources: ["namespaces", "pods"]
     verbs: ["get", "list", "watch"]
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
   name: pertisk-kube-readonly-binding
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: pertisk-kube-readonly
 subjects:
   - kind: ServiceAccount
     name: pertisk-kube-sa
     namespace: pertisk-kube

