apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pertisk-kube.labels" . | nindent 4 }}
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        {{- include "pertisk-kube.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      containers:
        - name: pertisk-kube
          image: "{{ .Values.app.image.registry }}/{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: STATIC_DIR
              value: "/app/static"
            - name: RUST_LOG
              value: {{ .Values.app.env.rustLog | default "info" }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          {{- if .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.app.resources }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- end }}
