apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pertisk-kube.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pertisk-kube.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.app.auth.username | default "admin" | b64enc | quote }}
  password: {{ .Values.app.auth.password | default "admin" | b64enc | quote }}
  jwt-secret: {{ .Values.app.auth.jwtSecret | default "your-secret-key-change-in-production" | b64enc | quote }}
