{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pertisk-kube.labels" . | nindent 4 }}
{{- end }}
