apiVersion: v2
name: pertisk-kube
description: A Helm chart for Pertisk Kubernetes Web Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - monitoring
  - dashboard
maintainers:
  - name: Pertisk Tech
